

name: jd_car 京东汽车
on:
  workflow_dispatch:
  schedule:
      - cron: "10 7 * * *"
  watch:
      types: [started]
  repository_dispatch:
      types: car
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Tenkai17/JD_Script.git ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: '运行 【京东汽车】'
        run: |
          cd ~/scripts
          node jd_car.js
