

name: jd_daily_egg 京东金融天天提额
on:
  workflow_dispatch:
  schedule:
      - cron: "22 16 * * *"
  watch:
      types: [started]
  repository_dispatch:
      types: daily_egg
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Tenkai17/JD_Script.git ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: '运行 【京东金融天天提额】'
        run: |
          cd ~/scripts
          node jd_daily_egg.js
