

name: jd_health 健康抽奖机【活动于2020-12-31日结束】
on:
  workflow_dispatch:
  schedule:
      - cron: "10 0 * * *"
  watch:
      types: [started]
  repository_dispatch:
      types: health
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Tenkai17/JD_Script.git ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: '运行 【健康抽奖机】'
        run: |
          cd ~/scripts
          node jd_health.js
