# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_unbind 注销京东会员卡

on:
  workflow_dispatch:
  schedule:
    - cron: '55 23 * * *'
  watch:
    types: started
  repository_dispatch:
    types: unbind
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Tenkai17/JD_Script.git ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: '运行 【注销京东会员卡】'
        run: |
          cd ~/scripts
          node jd_unbind.js
