

name: jx_sign 京喜签到
on:
  workflow_dispatch:
  schedule:
      - cron: "5 0 * * *"
  watch:
      types: [started]
  repository_dispatch:
      types: jx_sign
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Tenkai17/JD_Script.git ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: '运行 【京喜签到】'
        run: |
          cd ~/scripts
          node jx_sign.js
